import { describe, expect, test } from "bun:test";
import { createEditorHtml, EDITOR_CSS, EDITOR_JAVASCRIPT } from "../src/ui.ts";

describe("browser UI bindings", () => {
    test("declares every used element and references an existing HTML ID", () => {
        const html = createEditorHtml("Test Product", "test-session-token");
        const htmlIds = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]));
        const declarations = new Map([...EDITOR_JAVASCRIPT.matchAll(/^\s+([A-Za-z][A-Za-z0-9]*): requiredElement\("([^"]+)"\),$/gm)].map((match) => [match[1], match[2]]));
        const usedNames = new Set([...EDITOR_JAVASCRIPT.matchAll(/\belements\.([A-Za-z][A-Za-z0-9]*)/g)].map((match) => match[1]));

        expect(declarations.size).toBeGreaterThan(0);
        expect([...usedNames].filter((name) => !declarations.has(name))).toEqual([]);
        expect([...declarations.values()].filter((id) => !htmlIds.has(id))).toEqual([]);
        expect(html).not.toContain("{{");
        expect(html).toContain('<link rel="stylesheet" href="/app.css">');
        expect(html).toContain('<meta name="config-editor-session-token" content="test-session-token">');
        expect(html).toContain('<script type="module" src="/app.js"></script>');
        expect(EDITOR_CSS).toContain(":root");
        expect(EDITOR_JAVASCRIPT).toContain("createConfigurationEditor");
        expect(EDITOR_JAVASCRIPT).toContain('fetch("/app-translations.json")');
        expect(EDITOR_JAVASCRIPT).toContain("legacyOperationReport.textContent");
        expect(EDITOR_JAVASCRIPT).toContain('api("/api/snippet/preview"');
        expect(EDITOR_JAVASCRIPT).not.toContain('api("/api/snippet/apply"');
        expect(EDITOR_JAVASCRIPT).not.toContain('api("/api/snippet/import"');
        expect(EDITOR_JAVASCRIPT).not.toContain("window.confirm");
        expect(EDITOR_JAVASCRIPT).not.toContain('document.createElement(actionable ? "button"');
        expect(EDITOR_JAVASCRIPT).toContain('api("/api/draft"');
        expect(EDITOR_JAVASCRIPT).toContain('api("/api/validate-all"');
        expect(EDITOR_JAVASCRIPT).toContain('api("/api/quick-fix"');
        expect(EDITOR_JAVASCRIPT).toContain("window.setTimeout(() => notification.remove(), 5000)");
        expect(html).toContain('id="task-home"');
        expect(html).toContain('id="workflow-edit"');
        expect(html).toContain('id="raw-editor" class="code-editor"');
        expect(html).toContain('id="legacy-draft-editor" class="code-editor"');
        expect(html).toContain('id="legacy-target-profile"');
        expect(html).toContain('id="snippet-bindings"');
        expect(html).toContain('id="snippet-dialog"');
        expect(html).toContain('id="save-all"');
        expect(html).toContain('id="check-all"');
        expect(html).toContain('id="discard-dialog"');
        expect(html).toContain('id="all-problems-group"');
        expect(html).toContain('id="notifications"');
        expect(html).toContain('id="bottom-panel-content"');
        expect(html).not.toContain('data-tab="structured"');
        expect(html).not.toContain("<footer");
        expect(html).not.toContain('id="workflow-feedback"');
        expect(html).not.toContain("<textarea");
        expect(EDITOR_CSS).toContain(".tree button.selected");
        expect(EDITOR_CSS).toContain(".notification-stack");
        expect(EDITOR_CSS).toContain(".code-editor .cm-editor { height: 100%; min-height: 0; overflow: hidden;");
    });
});
