PRODUCT_CMAKE_TARGET=ControlSurfaceIntegrator
PRODUCT_DISPLAY_NAME=ReaControlSurface
PRODUCT_ID=reacontrolsurface
PRODUCT_RESOURCE_DIRECTORY=ReaControlSurface
PRODUCT_CONFIG_FILENAME=ReaControlSurface.ini
PRODUCT_LOG_FILENAME=ReaControlSurface.log
PRODUCT_EXTSTATE_PREFIX=ReaCtrlSurf
PRODUCT_REAPER_REGISTRATION_ID=ReaControlSurface
PRODUCT_PLUGIN_FILENAME=reaper_csurf_integrator
PRODUCT_SCRIPT_DIRECTORY=ReaControlSurface
PRODUCT_PACKAGE_PREFIX=ReaControlSurface
PRODUCT_BUNDLE_ID=com.gaabora.reacontrolsurface
PRODUCT_REPOSITORY_URL=https://github.com/gaabora/Reaper-ControlSurfaceIntegrator
PRODUCT_OSK_SCRIPT_FILENAME=OSK on-screen keyboard.lua
PRODUCT_OSD_SCRIPT_FILENAME=OSD on-screen display.lua
PRODUCT_NOTIFICATIONS_SCRIPT_FILENAME=Notifications.lua
PRODUCT_OSK_DEBUG_SCRIPT_FILENAME=OSK state debug.lua
PRODUCT_CONTROL_PANEL_SCRIPT_FILENAME=Control Panel.lua
PRODUCT_CONTROL_PANEL_ACTION_ID=REACTRLSURF_OPEN_CONTROL_PANEL
