# Canonical public product identity. Change public names and paths only here.

set(PRODUCT_CMAKE_TARGET "ControlSurfaceIntegrator")
set(PRODUCT_DISPLAY_NAME "ReaControlSurface")
set(PRODUCT_ID "reacontrolsurface")
set(PRODUCT_RESOURCE_DIRECTORY "ReaControlSurface")
set(PRODUCT_CONFIG_FILENAME "ReaControlSurface.ini")
set(PRODUCT_LOG_FILENAME "ReaControlSurface.log")
set(PRODUCT_EXTSTATE_PREFIX "ReaCtrlSurf")
set(PRODUCT_REAPER_REGISTRATION_ID "ReaControlSurface")
set(PRODUCT_PLUGIN_FILENAME "reaper_csurf_integrator")
set(PRODUCT_SCRIPT_DIRECTORY "ReaControlSurface")
set(PRODUCT_PACKAGE_PREFIX "ReaControlSurface")
set(PRODUCT_BUNDLE_ID "com.gaabora.reacontrolsurface")
set(PRODUCT_OSK_SCRIPT_FILENAME "ReaControlSurface OSK on-screen keyboard.lua")
set(PRODUCT_OSD_SCRIPT_FILENAME "ReaControlSurface OSD on-screen display.lua")
set(PRODUCT_OSK_DEBUG_SCRIPT_FILENAME "ReaControlSurface OSK state debug.lua")

set(PRODUCT_PLUGIN_INSTALL_DIRECTORY "UserPlugins")
set(PRODUCT_SCRIPT_INSTALL_DIRECTORY "Scripts/${PRODUCT_SCRIPT_DIRECTORY}")
set(PRODUCT_OSK_SCRIPT_RESOURCE_PATH "/${PRODUCT_SCRIPT_INSTALL_DIRECTORY}/${PRODUCT_OSK_SCRIPT_FILENAME}")
set(PRODUCT_OSD_SCRIPT_RESOURCE_PATH "/${PRODUCT_SCRIPT_INSTALL_DIRECTORY}/${PRODUCT_OSD_SCRIPT_FILENAME}")

set(PRODUCT_EXTSTATE_OSK "${PRODUCT_EXTSTATE_PREFIX}_OSK")
set(PRODUCT_EXTSTATE_OSK_COMMAND "${PRODUCT_EXTSTATE_PREFIX}_OSK_CMD")
set(PRODUCT_EXTSTATE_OSK_SETTINGS "${PRODUCT_EXTSTATE_PREFIX}_OSK_SETTINGS")
set(PRODUCT_EXTSTATE_OSD "${PRODUCT_EXTSTATE_PREFIX}_OSD")
set(PRODUCT_EXTSTATE_OSD_SETTINGS "${PRODUCT_EXTSTATE_PREFIX}_OSD_SETTINGS")

set(PRODUCT_IDENTITY_REQUIRED_VALUES
  PRODUCT_CMAKE_TARGET
  PRODUCT_DISPLAY_NAME
  PRODUCT_ID
  PRODUCT_RESOURCE_DIRECTORY
  PRODUCT_CONFIG_FILENAME
  PRODUCT_LOG_FILENAME
  PRODUCT_EXTSTATE_PREFIX
  PRODUCT_REAPER_REGISTRATION_ID
  PRODUCT_PLUGIN_FILENAME
  PRODUCT_SCRIPT_DIRECTORY
  PRODUCT_PACKAGE_PREFIX
  PRODUCT_BUNDLE_ID
  PRODUCT_OSK_SCRIPT_FILENAME
  PRODUCT_OSD_SCRIPT_FILENAME
  PRODUCT_OSK_DEBUG_SCRIPT_FILENAME
)

foreach(PRODUCT_IDENTITY_VALUE IN LISTS PRODUCT_IDENTITY_REQUIRED_VALUES)
  if(NOT DEFINED ${PRODUCT_IDENTITY_VALUE} OR "${${PRODUCT_IDENTITY_VALUE}}" STREQUAL "")
    message(FATAL_ERROR "Product identity value ${PRODUCT_IDENTITY_VALUE} must not be empty")
  endif()
endforeach()

if(NOT PRODUCT_ID MATCHES "^[a-z0-9][a-z0-9_-]*$")
  message(FATAL_ERROR "PRODUCT_ID must match [a-z0-9][a-z0-9_-]*")
endif()

foreach(PRODUCT_IDENTITY_PATH_VALUE PRODUCT_RESOURCE_DIRECTORY PRODUCT_CONFIG_FILENAME PRODUCT_LOG_FILENAME PRODUCT_PLUGIN_FILENAME PRODUCT_SCRIPT_DIRECTORY PRODUCT_PACKAGE_PREFIX PRODUCT_OSK_SCRIPT_FILENAME PRODUCT_OSD_SCRIPT_FILENAME PRODUCT_OSK_DEBUG_SCRIPT_FILENAME)
  if("${${PRODUCT_IDENTITY_PATH_VALUE}}" MATCHES "[/\\\\]")
    message(FATAL_ERROR "Product identity value ${PRODUCT_IDENTITY_PATH_VALUE} must be one path component")
  endif()
endforeach()
