set(PRODUCT_IDENTITY_REQUIRED_VALUES
  PRODUCT_CMAKE_TARGET
  PRODUCT_DISPLAY_NAME
  PRODUCT_ID
  PRODUCT_RESOURCE_DIRECTORY
  PRODUCT_CONFIG_FILENAME
  PRODUCT_LOG_FILENAME
  PRODUCT_EXTSTATE_PREFIX
  PRODUCT_REAPER_REGISTRATION_ID
  PRODUCT_PLUGIN_FILENAME
  PRODUCT_SCRIPT_DIRECTORY
  PRODUCT_PACKAGE_PREFIX
  PRODUCT_BUNDLE_ID
  PRODUCT_OSK_SCRIPT_FILENAME
  PRODUCT_OSD_SCRIPT_FILENAME
  PRODUCT_OSK_DEBUG_SCRIPT_FILENAME
)

get_filename_component(PRODUCT_IDENTITY_FILE "${CMAKE_CURRENT_LIST_DIR}/../Scripts/product_identity.conf" ABSOLUTE)
if(NOT EXISTS "${PRODUCT_IDENTITY_FILE}")
  message(FATAL_ERROR "Product identity file does not exist: ${PRODUCT_IDENTITY_FILE}")
endif()

file(STRINGS "${PRODUCT_IDENTITY_FILE}" PRODUCT_IDENTITY_LINES)
set(PRODUCT_IDENTITY_SEEN_KEYS)
foreach(PRODUCT_IDENTITY_LINE IN LISTS PRODUCT_IDENTITY_LINES)
  string(STRIP "${PRODUCT_IDENTITY_LINE}" PRODUCT_IDENTITY_LINE)
  if(PRODUCT_IDENTITY_LINE STREQUAL "" OR PRODUCT_IDENTITY_LINE MATCHES "^#")
    continue()
  endif()
  if(NOT PRODUCT_IDENTITY_LINE MATCHES "^([A-Z0-9_]+)=(.*)$")
    message(FATAL_ERROR "Invalid product identity line: ${PRODUCT_IDENTITY_LINE}")
  endif()
  set(PRODUCT_IDENTITY_KEY "${CMAKE_MATCH_1}")
  set(PRODUCT_IDENTITY_VALUE "${CMAKE_MATCH_2}")
  list(FIND PRODUCT_IDENTITY_REQUIRED_VALUES "${PRODUCT_IDENTITY_KEY}" PRODUCT_IDENTITY_KEY_INDEX)
  if(PRODUCT_IDENTITY_KEY_INDEX EQUAL -1)
    message(FATAL_ERROR "Unknown product identity key: ${PRODUCT_IDENTITY_KEY}")
  endif()
  list(FIND PRODUCT_IDENTITY_SEEN_KEYS "${PRODUCT_IDENTITY_KEY}" PRODUCT_IDENTITY_KEY_INDEX)
  if(NOT PRODUCT_IDENTITY_KEY_INDEX EQUAL -1)
    message(FATAL_ERROR "Duplicate product identity key: ${PRODUCT_IDENTITY_KEY}")
  endif()
  list(APPEND PRODUCT_IDENTITY_SEEN_KEYS "${PRODUCT_IDENTITY_KEY}")
  set(${PRODUCT_IDENTITY_KEY} "${PRODUCT_IDENTITY_VALUE}")
endforeach()

foreach(PRODUCT_IDENTITY_VALUE IN LISTS PRODUCT_IDENTITY_REQUIRED_VALUES)
  if(NOT DEFINED ${PRODUCT_IDENTITY_VALUE} OR "${${PRODUCT_IDENTITY_VALUE}}" STREQUAL "")
    message(FATAL_ERROR "Product identity value ${PRODUCT_IDENTITY_VALUE} must not be empty")
  endif()
endforeach()

set(PRODUCT_PLUGIN_INSTALL_DIRECTORY "UserPlugins")
set(PRODUCT_SCRIPT_INSTALL_DIRECTORY "Scripts/${PRODUCT_SCRIPT_DIRECTORY}")
set(PRODUCT_OSK_SCRIPT_RESOURCE_PATH "/${PRODUCT_SCRIPT_INSTALL_DIRECTORY}/${PRODUCT_OSK_SCRIPT_FILENAME}")
set(PRODUCT_OSD_SCRIPT_RESOURCE_PATH "/${PRODUCT_SCRIPT_INSTALL_DIRECTORY}/${PRODUCT_OSD_SCRIPT_FILENAME}")

set(PRODUCT_EXTSTATE_OSK "${PRODUCT_EXTSTATE_PREFIX}_OSK")
set(PRODUCT_EXTSTATE_OSK_COMMAND "${PRODUCT_EXTSTATE_PREFIX}_OSK_CMD")
set(PRODUCT_EXTSTATE_OSK_SETTINGS "${PRODUCT_EXTSTATE_PREFIX}_OSK_SETTINGS")
set(PRODUCT_EXTSTATE_OSD "${PRODUCT_EXTSTATE_PREFIX}_OSD")
set(PRODUCT_EXTSTATE_OSD_SETTINGS "${PRODUCT_EXTSTATE_PREFIX}_OSD_SETTINGS")

if(NOT PRODUCT_ID MATCHES "^[a-z0-9][a-z0-9_-]*$")
  message(FATAL_ERROR "PRODUCT_ID must match [a-z0-9][a-z0-9_-]*")
endif()

foreach(PRODUCT_IDENTITY_PATH_VALUE PRODUCT_RESOURCE_DIRECTORY PRODUCT_CONFIG_FILENAME PRODUCT_LOG_FILENAME PRODUCT_PLUGIN_FILENAME PRODUCT_SCRIPT_DIRECTORY PRODUCT_PACKAGE_PREFIX PRODUCT_OSK_SCRIPT_FILENAME PRODUCT_OSD_SCRIPT_FILENAME PRODUCT_OSK_DEBUG_SCRIPT_FILENAME)
  if("${${PRODUCT_IDENTITY_PATH_VALUE}}" MATCHES "[/\\\\]")
    message(FATAL_ERROR "Product identity value ${PRODUCT_IDENTITY_PATH_VALUE} must be one path component")
  endif()
endforeach()
